"""add public_at

Revision ID: 24ce04920b71
Revises: a7f97e0ab4c4
Create Date: 2020-03-29 09:30:47.406342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ce04920b71'
down_revision = 'a7f97e0ab4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('public_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'public_at')
    # ### end Alembic commands ###
