"""add friend

Revision ID: bf90a28c6f46
Revises: 57625377bafb
Create Date: 2020-04-01 18:29:19.314704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf90a28c6f46'
down_revision = '57625377bafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('friend_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.UniqueConstraint('user_id', 'friend_id', name='unique_friendships')
                    )
    op.create_index(op.f('ix_friendships_user_id'), 'friendships', ['user_id'], unique=False)
    op.add_column('users', sa.Column('invite_code', sa.String(), nullable=True))

    # with op.batch_alter_table("users") as batch_op:
    #     batch_op.create_unique_constraint('users', ['invite_code'])
    op.create_unique_constraint(None, 'users', ['invite_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'invite_code')
    op.drop_index(op.f('ix_friendships_user_id'), table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###
