name: Codecov
on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master, dev ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend/app
    steps:
    - uses: actions/checkout@master
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: 3.6

    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pip install pytest-asyncio
        pip install -r requirements.txt
        pytest --cov=./app --cov-report=xml --disable-warnings
      working-directory: ${{env.working-directory}}

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ${{env.working-directory}}/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true