name: CI2

on:
  push:
    branches: [ test/deployNuxt ]

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run frontend branch
      run: git filter-branch --subdirectory-filter app -- --all
        
    - name: Add production environment variable
      run : |
        echo "BASE_URL='https://${{secrets.HEROKU_API_APP_NAME}}'.herokuapp.com/" >> ./src/configs/.env.prod
        echo "BROWSER_BASE_URL='https://${{secrets.HEROKU_API_APP_NAME}}'.herokuapp.com/" >> ./src/configs/.env.prod
        
    - uses: akhileshns/heroku-deploy@v3.0.0
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
